/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Destination de l\'acquisition.
 */
export type AcquisitionDestination = 'MAIN_PROPERTY' | 'SECONDARY_PROPERTY' | 'RENTAL_PROPERTY' | 'PROFESSIONAL_PROPERTY' | 'VIAGER' | 'INVESTMENT';

export const AcquisitionDestination = {
    MainProperty: 'MAIN_PROPERTY' as AcquisitionDestination,
    SecondaryProperty: 'SECONDARY_PROPERTY' as AcquisitionDestination,
    RentalProperty: 'RENTAL_PROPERTY' as AcquisitionDestination,
    ProfessionalProperty: 'PROFESSIONAL_PROPERTY' as AcquisitionDestination,
    Viager: 'VIAGER' as AcquisitionDestination,
    Investment: 'INVESTMENT' as AcquisitionDestination
};

