/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * État de l\'acquisition.
 */
export type AcquisitionState = 'VEFA' | 'SOCIAL' | 'UNDER_CONSTRUCTION' | 'RAW_LAND' | 'NEW' | 'OLD_WITH_WORKS' | 'OLD' | 'WORKS';

export const AcquisitionState = {
    Vefa: 'VEFA' as AcquisitionState,
    Social: 'SOCIAL' as AcquisitionState,
    UnderConstruction: 'UNDER_CONSTRUCTION' as AcquisitionState,
    RawLand: 'RAW_LAND' as AcquisitionState,
    New: 'NEW' as AcquisitionState,
    OldWithWorks: 'OLD_WITH_WORKS' as AcquisitionState,
    Old: 'OLD' as AcquisitionState,
    Works: 'WORKS' as AcquisitionState
};

