/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PartnerType } from './partnerType';
import { Address } from './address';
import { Contact } from './contact';


/**
 * Partenaire bancaire actif: il s\'agit d\'un partenaire issue de la base de partenaires, ayant un role sur le dossier courant.
 */
export interface ActivePartner { 
    type?: PartnerType;
    /**
     * ID unique du partenaire.
     */
    id?: string;
    /**
     * Nom du partenaire.
     */
    name?: string;
    address?: Address;
    contact?: Contact;
    main_contact?: Contact;
    /**
     * Email du partenaire.
     */
    email?: string;
    /**
     * Numéro de téléphone du partenaire.
     */
    phone_number?: string;
    /**
     * Role de ce partenaire: côté acheteur, coté vendeur, ou leader si plusieurs partenaires d\'un même type existent.
     */
    role?: ActivePartner.RoleEnum;
    /**
     * Sous-entité: agence, etc....
     */
    sub_entity?: string;
    /**
     * Agrément ORIAS, ou n\'importe quelle référence légale.
     */
    agreement_number?: string;
    /**
     * Lien vers le logo du partenaire. Par exemple: https://www.toaztr.com/assets/toaztr_logo.png
     */
    logo_uri?: string;
    /**
     * Commentaire.
     */
    comment?: string;
}
export namespace ActivePartner {
    export type RoleEnum = 'BUYER_SIDE' | 'SELLER_SIDE' | 'LEADER';
    export const RoleEnum = {
        BuyerSide: 'BUYER_SIDE' as RoleEnum,
        SellerSide: 'SELLER_SIDE' as RoleEnum,
        Leader: 'LEADER' as RoleEnum
    };
}


