/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Address } from './address';
import { AcquisitionState } from './acquisitionState';
import { AcquisitionDestination } from './acquisitionDestination';
import { ProjectDates } from './projectDates';
import { AcquisitionNature } from './acquisitionNature';


/**
 * Informations diverses, dont administratives, relatives au projet.
 */
export interface AdministrativeInformation { 
    nature?: AcquisitionNature;
    state?: AcquisitionState;
    destination?: AcquisitionDestination;
    address?: Address;
    project_dates?: ProjectDates;
    /**
     * Parcelle cadastrale.
     */
    land_register_reference?: string;
    /**
     * Description du bien.
     */
    description?: string;
}

