/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdministrativeInformation } from './administrativeInformation';
import { UndividedPerson } from './undividedPerson';
import { BalancingAdjustmentExpenses } from './balancingAdjustmentExpenses';
import { DpeRate } from './dpeRate';
import { Surfaces } from './surfaces';
import { ProjectState } from './projectState';
import { ConstructionNorms } from './constructionNorms';


/**
 * Projet de rachat de soulte.
 */
export interface BalancingAdjustment { 
    type: BalancingAdjustment.TypeEnum;
    project_state?: ProjectState;
    administrative_information?: AdministrativeInformation;
    surfaces?: Surfaces;
    dpe_rate?: DpeRate;
    /**
     * Date de construction, pour les logements achevés.
     */
    construction_date?: string;
    construction_norm?: ConstructionNorms;
    /**
     * Numéro de lot.
     */
    lot_number?: string;
    /**
     * Nombre de pièces.
     */
    rooms_count?: number;
    undivided_persons?: Array<UndividedPerson>;
    expenses?: BalancingAdjustmentExpenses;
}
export namespace BalancingAdjustment {
    export type TypeEnum = 'BALANCING_ADJUSTMENT';
    export const TypeEnum = {
        BalancingAdjustment: 'BALANCING_ADJUSTMENT' as TypeEnum
    };
}


