/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RIB } from './rIB';


/**
 * Informations bancaires d\'un emprunteur.
 */
export interface BankInfo { 
    /**
     * Nom de l\'agence.
     */
    current_agency?: string;
    /**
     * Nom de la banque actuelle.
     */
    current_bank?: string;
    /**
     * Date depuis laquelle l\'emprunteur est client de sa banque actuelle.
     */
    customer_since?: string;
    /**
     * Département (75, 13, ...) de la banque actuelle.
     */
    departement?: string;
    rib?: RIB;
}

