/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Insurance } from './insurance';
import { Guaranty } from './guaranty';


/**
 * Prêt relais.   Il est à noter que cet objet peut matérialiser un prêt relais ou un prêt in-fine, ces 2 prêts étants définis de manière identique au sein d\'un plan de financement. Les caractéristiques de ces 2 prêts (période de différé partiel ou total et remboursement du capital en une seule fois à la fin du prêt) sont en effet identiques. Seuls changent l\'objet du prêt, et ce à quoi le prêt est adossé (un bien immobilier, le nantissement d\'un plancement financier...).  Par défaut, le différé est partiel.
 */
export interface BridgeLoan { 
    /**
     * Type de prêt: prêt relais.
     */
    type: BridgeLoan.TypeEnum;
    /**
     * Montant du prêt relais.
     */
    amount: number;
    /**
     * Taux d\'intérêt annuel en %. Mettre 2.1 pour 2.1% par exemple.
     */
    yearly_rate: number;
    /**
     * Durée du prêt relais, en mois.
     */
    duration_months: number;
    /**
     * Type de différé: partiel (différé d\'amortissement uniquement) ou total (différé d\'amortissement et d\'intérets).
     */
    grace_period_type?: BridgeLoan.GracePeriodTypeEnum;
    /**
     * Assurance(s) emprunteur(s).
     */
    insurances?: Array<Insurance>;
    guaranty?: Guaranty;
    /**
     * Nom du prêt: tout type d\'identification (appellation marketing, etc...)
     */
    loan_name?: string;
}
export namespace BridgeLoan {
    export type TypeEnum = 'BRIDGE_LOAN';
    export const TypeEnum = {
        BridgeLoan: 'BRIDGE_LOAN' as TypeEnum
    };
    export type GracePeriodTypeEnum = 'PARTIAL' | 'TOTAL';
    export const GracePeriodTypeEnum = {
        Partial: 'PARTIAL' as GracePeriodTypeEnum,
        Total: 'TOTAL' as GracePeriodTypeEnum
    };
}


