/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdministrativeInformation } from './administrativeInformation';
import { BudgetExpenses } from './budgetExpenses';
import { DpeRate } from './dpeRate';


/**
 * Projet de type budget, lorsque l\'emprunteur est encore en phase de recherche, avant qu\'un bien soit identifié.
 */
export interface Budget { 
    type: Budget.TypeEnum;
    administrative_information?: AdministrativeInformation;
    dpe_rate?: DpeRate;
    expenses?: BudgetExpenses;
    /**
     * Commentaires relatif au projet.
     */
    comment?: string;
}
export namespace Budget {
    export type TypeEnum = 'BUDGET';
    export const TypeEnum = {
        Budget: 'BUDGET' as TypeEnum
    };
}


