/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BudgetParameters } from './budgetParameters';
import { BudgetResults } from './budgetResults';


/**
 * Réponse d\'un calcul de budget.
 */
export interface BudgetSimulation { 
    /**
     * Type de simulation.
     */
    type: BudgetSimulation.TypeEnum;
    parameters: BudgetParameters;
    results?: BudgetResults;
}
export namespace BudgetSimulation {
    export type TypeEnum = 'BUDGET';
    export const TypeEnum = {
        Budget: 'BUDGET' as TypeEnum
    };
}


