/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CallForFunds } from './callForFunds';


/**
 * Calendrier d\'appels de fonds, dans le cadre d\'un contrat CCMI par exemple.
 */
export interface CallsForFunds { 
    /**
     * Type de déblocage. Minimisation des coûts: les fonds sont puisées dans les prêts les moins chers en premier (dans la mesure du possible). Proportionnellement: les fonds sont puisés dans chacun des prêts, proportionnellement aux montants des prêts.
     */
    type: CallsForFunds.TypeEnum;
    /**
     * Dates (mois), montants et finalités des tranches de déblocage.
     */
    calls: Array<CallForFunds>;
}
export namespace CallsForFunds {
    export type TypeEnum = 'PROPORTIONAL' | 'INCREASING_RATE';
    export const TypeEnum = {
        Proportional: 'PROPORTIONAL' as TypeEnum,
        IncreasingRate: 'INCREASING_RATE' as TypeEnum
    };
}


