/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * État de l\'avancement du dossier.
 */
export type CaseStatus = 'NEW' | 'INSTRUCTION' | 'SENT_TO_BANK' | 'GRANTED_BANK' | 'REFUSED_BANK' | 'CUSTOMER_ACCEPTED' | 'COMPLETED' | 'INVOICED' | 'CLOSED' | 'CANCELED';

export const CaseStatus = {
    New: 'NEW' as CaseStatus,
    Instruction: 'INSTRUCTION' as CaseStatus,
    SentToBank: 'SENT_TO_BANK' as CaseStatus,
    GrantedBank: 'GRANTED_BANK' as CaseStatus,
    RefusedBank: 'REFUSED_BANK' as CaseStatus,
    CustomerAccepted: 'CUSTOMER_ACCEPTED' as CaseStatus,
    Completed: 'COMPLETED' as CaseStatus,
    Invoiced: 'INVOICED' as CaseStatus,
    Closed: 'CLOSED' as CaseStatus,
    Canceled: 'CANCELED' as CaseStatus
};

