/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LMNP } from './lMNP';
import { HouseConstruction } from './houseConstruction';
import { Pinel } from './pinel';
import { BalancingAdjustment } from './balancingAdjustment';
import { NewProperty } from './newProperty';
import { LegalPerson } from './legalPerson';
import { ActivePartner } from './activePartner';
import { OldProperty } from './oldProperty';
import { Land } from './land';
import { CaseCandidateSimulations } from './caseCandidateSimulations';
import { DebtConsolidation } from './debtConsolidation';
import { CaseStatus } from './caseStatus';
import { Budget } from './budget';
import { HouseholdDetails } from './householdDetails';
import { Works } from './works';


/**
 * Dossier emprunteur complet.
 */
export interface Case { 
    /**
     * Nom du dossier
     */
    name?: string;
    /**
     * ID de l\'utilisateur à qui est assigné le dossier
     */
    assigned_to?: string;
    /**
     * ID du dossier parent, si ce dossier a été créé par copie
     */
    copied_from?: string;
    status?: CaseStatus;
    /**
     * Commentaire sur le dossier
     */
    comment?: string;
    candidate_simulations?: Array<CaseCandidateSimulations>;
    actor?: HouseholdDetails | LegalPerson;
    /**
     * Liste des intervenants sur le dossier: notaire, courtier, conseiller clientèle banque, agent immobilier, etc...
     */
    partners?: Array<ActivePartner>;
    /**
     * Projet.
     */
    project?: Budget | HouseConstruction | OldProperty | NewProperty | Works | Land | DebtConsolidation | Pinel | BalancingAdjustment | LMNP;
}

