/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Normes énergétique des constructions.
 */
export type ConstructionNorms = 'RT_2020' | 'HPE_2012' | 'RT_2012' | 'BBC_RENOV_2009' | 'HPE_RENOV_2009' | 'RT_2005' | 'RT_ANTERIEUR';

export const ConstructionNorms = {
    Rt2020: 'RT_2020' as ConstructionNorms,
    Hpe2012: 'HPE_2012' as ConstructionNorms,
    Rt2012: 'RT_2012' as ConstructionNorms,
    BbcRenov2009: 'BBC_RENOV_2009' as ConstructionNorms,
    HpeRenov2009: 'HPE_RENOV_2009' as ConstructionNorms,
    Rt2005: 'RT_2005' as ConstructionNorms,
    RtAnterieur: 'RT_ANTERIEUR' as ConstructionNorms
};

