/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CaseSummary } from './caseSummary';
import { RIB } from './rIB';
import { Partner } from './partner';


/**
 * Facture vers un client.
 */
export interface CustomerBill { 
    /**
     * Type de facture: partenaire.
     */
    type: CustomerBill.TypeEnum;
    partner: Partner;
    /**
     * Date d\'échéance.
     */
    due_date: string;
    /**
     * Montant de la facture.
     */
    amount: number;
    rib?: RIB;
    case_summary?: CaseSummary;
}
export namespace CustomerBill {
    export type TypeEnum = 'CUSTOMER_BILL';
    export const TypeEnum = {
        CustomerBill: 'CUSTOMER_BILL' as TypeEnum
    };
}


