/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FundingResults } from './fundingResults';
import { Partner } from './partner';
import { Case } from './case';


/**
 * Paramètres permettant de générer une facture à destination d\'un client.
 */
export interface CustomerBillingParameters { 
    /**
     * Type de paramètres de faturation.
     */
    type: CustomerBillingParameters.TypeEnum;
    funding_results: FundingResults;
    _case: Case;
    partner: Partner;
}
export namespace CustomerBillingParameters {
    export type TypeEnum = 'CUSTOMER_BILLING_PARAMETERS';
    export const TypeEnum = {
        CustomerBillingParameters: 'CUSTOMER_BILLING_PARAMETERS' as TypeEnum
    };
}


