/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BudgetExpenses } from './budgetExpenses';
import { LoanToConsolidate } from './loanToConsolidate';


/**
 * Projet de rachat ou de regroupement de crédits.
 */
export interface DebtConsolidation { 
    type: DebtConsolidation.TypeEnum;
    /**
     * Liste du ou des prêts à racheter.
     */
    loans_to_consolidate?: Array<LoanToConsolidate>;
    expenses?: BudgetExpenses;
}
export namespace DebtConsolidation {
    export type TypeEnum = 'DEBT_CONSOLIDATION';
    export const TypeEnum = {
        DebtConsolidation: 'DEBT_CONSOLIDATION' as TypeEnum
    };
}


