/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoanRemainingCosts } from './loanRemainingCosts';
import { Log } from './log';
import { FundingResults } from './fundingResults';


/**
 * Résultats d\'un rachat ou regroupement de crédits.
 */
export interface DebtConsolidationResults { 
    funding_plan?: FundingResults;
    /**
     * Liste des montants restant à payer, des prêts à racheters (capital, assurance, intérets, IRA).
     */
    loans_remaining_costs?: Array<LoanRemainingCosts>;
    /**
     * Différence entre l\'assurance restant à payer sur le ou les crédits rachetés et l\'assurance du nouveau crédit (une valeur positive représente un gain financier).
     */
    insurance_gain?: number;
    /**
     * Différence entre les intérêts restants à payer sur le ou les crédits rachetés et les intérets du nouveau crédit (une valeur positive représente un gain financier).
     */
    interests_gain?: number;
    /**
     * Différence ente l\'ensemble des coûts restants à payer sur le ou les crédits rachetés (intérets et assurance) et l\'ensemble des coût du nouveau crédit (intérêts, assurance, ira, frais de dossier et de courtage, frais de garantie). Une valeur positive représente un gain financier.
     */
    total_gain?: number;
    logs?: Array<Log>;
}

