/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Personne à charge, différente des enfants mineurs.
 */
export interface DependentPerson { 
    /**
     * Type de personne à charge.
     */
    type: DependentPerson.TypeEnum;
    /**
     * Commentaire.
     */
    comment?: string;
}
export namespace DependentPerson {
    export type TypeEnum = 'MOTHER' | 'FATHER' | 'OTHER';
    export const TypeEnum = {
        Mother: 'MOTHER' as TypeEnum,
        Father: 'FATHER' as TypeEnum,
        Other: 'OTHER' as TypeEnum
    };
}


