/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Note du diagnostique de performance énergétique (DPE).
 */
export type DpeRate = 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'VIERGE';

export const DpeRate = {
    A: 'A' as DpeRate,
    B: 'B' as DpeRate,
    C: 'C' as DpeRate,
    D: 'D' as DpeRate,
    E: 'E' as DpeRate,
    F: 'F' as DpeRate,
    G: 'G' as DpeRate,
    Vierge: 'VIERGE' as DpeRate
};

