/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Address } from './address';


/**
 * Details professionnels d\'un emprunteur employée.
 */
export interface Employee { 
    /**
     * Type de travailleur.
     */
    type: Employee.TypeEnum;
    /**
     * Type de contrat.
     */
    contract_type?: Employee.ContractTypeEnum;
    /**
     * Particularité du contrat.
     */
    sub_contract_type?: Employee.SubContractTypeEnum;
    /**
     * Profession.
     */
    profession?: string;
    /**
     * Nom de l\'employeur actuel.
     */
    employer?: string;
    employer_address?: Address;
    /**
     * Date d\'embauche.
     */
    hiring_date?: string;
    /**
     * Nombre d\'employés dans l\'entreprise employeuse.
     */
    employees_number?: number;
    /**
     * Date de fin contrat, pour les CDD.
     */
    end_contract_date?: string;
    /**
     * Date de fin de la période d\'essai.
     */
    end_trial_date?: string;
}
export namespace Employee {
    export type TypeEnum = 'EMPLOYEE';
    export const TypeEnum = {
        Employee: 'EMPLOYEE' as TypeEnum
    };
    export type ContractTypeEnum = 'CDD' | 'CDI' | 'CIVIL_SERVANT' | 'OTHER';
    export const ContractTypeEnum = {
        Cdd: 'CDD' as ContractTypeEnum,
        Cdi: 'CDI' as ContractTypeEnum,
        CivilServant: 'CIVIL_SERVANT' as ContractTypeEnum,
        Other: 'OTHER' as ContractTypeEnum
    };
    export type SubContractTypeEnum = 'TRIAL_PERIOD' | 'TITULAR_CIVIL_SERVANT' | 'CONTRACTUAL_CIVIL_SERVANT' | 'VACATAIRE_CIVIL_SERVANT' | 'INTERIM' | 'INTERN';
    export const SubContractTypeEnum = {
        TrialPeriod: 'TRIAL_PERIOD' as SubContractTypeEnum,
        TitularCivilServant: 'TITULAR_CIVIL_SERVANT' as SubContractTypeEnum,
        ContractualCivilServant: 'CONTRACTUAL_CIVIL_SERVANT' as SubContractTypeEnum,
        VacataireCivilServant: 'VACATAIRE_CIVIL_SERVANT' as SubContractTypeEnum,
        Interim: 'INTERIM' as SubContractTypeEnum,
        Intern: 'INTERN' as SubContractTypeEnum
    };
}


