/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MaritalStatus } from './maritalStatus';


/**
 * Situation familiale.
 */
export interface FamilySituation { 
    marital_status?: MaritalStatus;
    /**
     * Date du dernier changement de statut marital.
     */
    marital_status_since?: string;
    /**
     * A compléter si cette personne est en relation avec un autre emprunteur.
     */
    is_in_relation_with?: string;
    /**
     * Régime matrimonial.
     */
    matrimony_regime?: FamilySituation.MatrimonyRegimeEnum;
    /**
     * Type de procédure de divorce, si la procédure est en cours.
     */
    divorce_procedure?: FamilySituation.DivorceProcedureEnum;
    /**
     * Pays dans lequel le mariage a eu lieu.
     */
    marital_country?: string;
}
export namespace FamilySituation {
    export type MatrimonyRegimeEnum = 'NOT_APPLICABLE' | 'COMMUNAUTE_REDUITE_AUX_ACQUETS' | 'COMMUNAUTE_DE_MEUBLES_ET_ACQUETS' | 'COMMUNAUTE_UNIVERSELLE' | 'PARTICIPATION_AUX_ACQUETS' | 'SEPARATION_DE_BIEN';
    export const MatrimonyRegimeEnum = {
        NotApplicable: 'NOT_APPLICABLE' as MatrimonyRegimeEnum,
        CommunauteReduiteAuxAcquets: 'COMMUNAUTE_REDUITE_AUX_ACQUETS' as MatrimonyRegimeEnum,
        CommunauteDeMeublesEtAcquets: 'COMMUNAUTE_DE_MEUBLES_ET_ACQUETS' as MatrimonyRegimeEnum,
        CommunauteUniverselle: 'COMMUNAUTE_UNIVERSELLE' as MatrimonyRegimeEnum,
        ParticipationAuxAcquets: 'PARTICIPATION_AUX_ACQUETS' as MatrimonyRegimeEnum,
        SeparationDeBien: 'SEPARATION_DE_BIEN' as MatrimonyRegimeEnum
    };
    export type DivorceProcedureEnum = 'MUTUAL_CONSENT' | 'JUDICIAL_MUTUAL_CONSENT';
    export const DivorceProcedureEnum = {
        MutualConsent: 'MUTUAL_CONSENT' as DivorceProcedureEnum,
        JudicialMutualConsent: 'JUDICIAL_MUTUAL_CONSENT' as DivorceProcedureEnum
    };
}


