/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectDates } from './projectDates';
import { ActivePartner } from './activePartner';


/**
 * Détails relatifs à la mise en vente d\'un bien immobilier.
 */
export interface ForSale { 
    /**
     * Prix public de mise en vente.
     */
    price?: number;
    /**
     * Frais d\'agence à la charge du vendeur, et venant donc se retrancher au prix public de mise en vente.
     */
    agency_fees?: number;
    /**
     * Montant de l\'impot éventuel sur le prix de vente, et venant donc se retrancher au prix public de mise en vente.
     */
    taxes?: number;
    /**
     * Depuis quelle date le bien est-il à vendre.
     */
    since?: string;
    dates?: ProjectDates;
    /**
     * Agence(s) en charge de la vente.
     */
    agencies?: Array<ActivePartner>;
    /**
     * Notaire(s) en charge de la vente.
     */
    notaries?: Array<ActivePartner>;
}

