/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Insurance } from './insurance';
import { Guaranty } from './guaranty';
import { GracePeriod } from './gracePeriod';
import { RatePeriod } from './ratePeriod';


/**
 * Prêt libre: prêt bancaire classique à amortissement, à taux fixe ou variable.   Il n\'est pas nécessaire de préciser le montant: le moteur de calcul le déterminera de façon optimale en fonction des postes de dépense du projet. Le montant ne doit être précisé que si celui-ci est fixé (par la banque, pour des contraintes légale, etc...).  En plus des caractéristiques habituelles (taux, durée, assurance et garantie), des caractéristiques d\'amortissement peuvent être précisées si nécessaire.
 */
export interface FreeLoan { 
    /**
     * Type de prêt: prêt libre.
     */
    type: FreeLoan.TypeEnum;
    /**
     * Taux d\'intérêt annuel en %. Mettre 2.1 pour 2.1% par exemple. Au moins l\'un de yearly_rate (dans le cas d\'un prêt à taux constant) ou yearly_rates (dans le cas d\'un prêt à taux variable) doit être précisé.
     */
    yearly_rate?: number;
    /**
     * Taux d\'intérêt annuels en %, dans le cadre d\'un prêt à taux variable. Mettre 2.1 pour 2.1% par exemple.
     */
    yearly_rates?: Array<RatePeriod>;
    /**
     * Durée maximale du prêt, en mois.
     */
    max_duration_months: number;
    /**
     * Assurance(s) emprunteur(s).
     */
    insurances?: Array<Insurance>;
    guaranty?: Guaranty;
    grace_period?: GracePeriod;
    /**
     * Amortissement mensuel maximal du prêt, (pour un prêt d\'amortissement mensuel constant, min_amortization = max_amortization).
     */
    max_amortization?: number;
    /**
     * Montant maximal du prêt, (pour un prêt de montant fixé, min_amount = max_amount).
     */
    max_amount?: number;
    /**
     * Amortissement mensuel minimal du prêt, (pour un prêt d\'amortissement mensuel constant, min_amortization = max_amortization).
     */
    min_amortization?: number;
    /**
     * Montant minimal du prêt, (pour un prêt de montant fixé, min_amount = max_amount).
     */
    min_amount?: number;
    /**
     * Nom du prêt: tout type d\'identification (appellation marketing, etc...)
     */
    loan_name?: string;
}
export namespace FreeLoan {
    export type TypeEnum = 'FREE_LOAN';
    export const TypeEnum = {
        FreeLoan: 'FREE_LOAN' as TypeEnum
    };
}


