/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Résultat de calcul de l\'impôt sur le revenu.
 */
export interface FrenchIncomeTaxResults { 
    /**
     * Montant de l\'impôt.
     */
    income_tax: number;
    /**
     * Numéro de la tranche marginale d\'imposition.
     */
    slice_number: number;
    /**
     * Taux moyen d\'imposition.
     */
    average_rate: number;
    /**
     * Contribution exceptionelle sur les hauts revenus.
     */
    cehr: number;
    /**
     * Coefficient familial.
     */
    family_coefficient: number;
    /**
     * Montant résiduel dans la tranche marginal, c\'est à dire montant avant de changer de tranche.
     */
    remaining_capacity_in_slice: number;
}

