/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MaritalStatus } from './maritalStatus';


/**
 * Paramètres de calcul de l\'impôt sur le revenu.
 */
export interface FrenchIncomeTaxParameters { 
    /**
     * Revenue fiscal de référence (fiscal_reference_revenue et net_monthly_revenue sont exclusifs).
     */
    fiscal_reference_revenue?: number;
    /**
     * Revenue mensuel net (fiscal_reference_revenue et net_monthly_revenue sont exclusifs).
     */
    net_monthly_revenue?: number;
    /**
     * Nombre d\'enfant(s) à charge.
     */
    children_in_charge?: number;
    marital_status?: MaritalStatus;
    /**
     * Application (ou pas) des 10% de déduction forfaitaire pour frais réels.
     */
    apply_ten_percent_discount?: boolean;
}

