/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Zone } from './zone';


/**
 * Résumé du plan de financement: valeurs, montants globaux et zone utilisée pour le calcul.
 */
export interface FundingResultsSummary { 
    /**
     * Montant maximal des mensualités, sur toute la durée du plan de financement.
     */
    effective_maximal_monthly_payment?: number;
    /**
     * Durée totale du plan de financement.
     */
    duration_months?: number;
    /**
     * Coût total des intérêts.
     */
    total_interests?: number;
    /**
     * Coût total des assurances.
     */
    total_insurances?: number;
    /**
     * Coût totals des garanties.
     */
    total_guaranty?: number;
    /**
     * Total des intérêts capitalisés, dans le cadre d\'un différé total.
     */
    total_capitalized_interests?: number;
    /**
     * Valeur du compteur d\'intérêts (ou de pré-amortissement), dans le cadre d\'un différé total.
     */
    total_preamortizations?: number;
    /**
     * Taux d\'endettement final de l\'emprunteur, calculé en considérant l\'ensemble de ses revenus, de ses charges, et du plan de financement. Une valeur a null signifie que le calcul est impossible (revenus non renseignés par exemple).
     */
    final_debt_ratio?: number;
    /**
     * Montant total de l\'apport personnel.
     */
    total_personal_funding?: number;
    /**
     * Montant total des revenus pondérés.
     */
    total_revenues?: number;
    /**
     * Montant total maximal des charges pondérées (celles-ci ayant une date de début et de fin, le maximum peut n\'être que ponctuel).
     */
    max_total_charges?: number;
    /**
     * Montant total des prêts persistants (ceux-ci ayant une date de début et de fin, le maximum peut n\'être que ponctuel).
     */
    max_total_persistant_loans?: number;
    /**
     * Montant minimal du reste à vivre.
     */
    min_remaining_for_living?: number;
    /**
     * Saut de charge.
     */
    jump_charge?: number;
    zone?: Zone;
}

