/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Loan } from './loan';
import { Log } from './log';
import { Taeg } from './taeg';
import { FundingResultsSummary } from './fundingResultsSummary';


/**
 * Résultats d\'un calcul de financement.
 */
export interface FundingResults { 
    /**
     * Status de la simulation: optimal (c\'est à dire qu\'un plan de financement a été trouvé) ou infaisable (la plupart du temps, enraison d\'une mensualité maximale trop basse).
     */
    status: FundingResults.StatusEnum;
    /**
     * Ligne(s) de crédit incluses dans le plan de financement.
     */
    loans?: Array<Loan>;
    taegs?: Taeg;
    summary?: FundingResultsSummary;
    logs?: Array<Log>;
}
export namespace FundingResults {
    export type StatusEnum = 'OPTIMAL' | 'INFEASIBLE';
    export const StatusEnum = {
        Optimal: 'OPTIMAL' as StatusEnum,
        Infeasible: 'INFEASIBLE' as StatusEnum
    };
}


