/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type de garantie du prêt.
 */
export type GuarantyType = 'HYPOTHEQUE' | 'IPPD' | 'CASDEN' | 'CREDIT_LOGEMENT_CLASSIC' | 'CREDIT_LOGEMENT_INITIO' | 'MGEN' | 'CUSTOM';

export const GuarantyType = {
    Hypotheque: 'HYPOTHEQUE' as GuarantyType,
    Ippd: 'IPPD' as GuarantyType,
    Casden: 'CASDEN' as GuarantyType,
    CreditLogementClassic: 'CREDIT_LOGEMENT_CLASSIC' as GuarantyType,
    CreditLogementInitio: 'CREDIT_LOGEMENT_INITIO' as GuarantyType,
    Mgen: 'MGEN' as GuarantyType,
    Custom: 'CUSTOM' as GuarantyType
};

