/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdministrativeInformation } from './administrativeInformation';
import { CallsForFunds } from './callsForFunds';
import { DpeRate } from './dpeRate';
import { Surfaces } from './surfaces';
import { ProjectState } from './projectState';
import { ConstructionNorms } from './constructionNorms';
import { Contact } from './contact';
import { HouseConstructionExpenses } from './houseConstructionExpenses';


/**
 * Project de construction de maison individuelle.
 */
export interface HouseConstruction { 
    type: HouseConstruction.TypeEnum;
    project_state?: ProjectState;
    administrative_information?: AdministrativeInformation;
    calls_for_funds?: CallsForFunds;
    surfaces?: Surfaces;
    /**
     * Date de livraison.
     */
    delivery_date?: string;
    seller?: Contact;
    dpe_rate?: DpeRate;
    construction_norm?: ConstructionNorms;
    /**
     * Numéro de lot.
     */
    lot_number?: string;
    /**
     * Nombre de pièces.
     */
    rooms_count?: number;
    expenses?: HouseConstructionExpenses;
}
export namespace HouseConstruction {
    export type TypeEnum = 'HOUSE_CONSTRUCTION';
    export const TypeEnum = {
        HouseConstruction: 'HOUSE_CONSTRUCTION' as TypeEnum
    };
}


