/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FinanceDetails } from './financeDetails';
import { DependentPerson } from './dependentPerson';
import { Child } from './child';
import { Person } from './person';
import { BankInfo } from './bankInfo';


/**
 * Détail relatifs au ménage. En cas de déclaration fiscale commune des différents emprunteurs, l\'information est à insérer dans cet objet.
 */
export interface HouseholdDetails { 
    type: HouseholdDetails.TypeEnum;
    /**
     * Liste des personnes du ménage (emprunteurs ou non).
     */
    persons?: Array<Person>;
    /**
     * Details relatifs aux enfants.
     */
    children?: Array<Child>;
    /**
     * Details relatifs aux personnes à charge.
     */
    dependent_persons?: Array<DependentPerson>;
    /**
     * Primo-accédant(s), ou assimilés (non-propriétaires de résidence principale depuis plus de 2 ans): oui/non.
     */
    first_time_buyer?: boolean;
    /**
     * Nombre de personnes au total dans le ménage.
     */
    people_count?: number;
    /**
     * Nombre d\'enfants dans le ménage: correspond à la taille de la liste d\'enfant.
     */
    children_count?: number;
    /**
     * Nombre de personnes dépendantes dans le ménage (hors enfants): correspond à la taille de la liste de personnes dépendantes.
     */
    dependent_persons_count?: number;
    finance?: FinanceDetails;
    bank_info?: BankInfo;
}
export namespace HouseholdDetails {
    export type TypeEnum = 'HOUSEHOLD';
    export const TypeEnum = {
        Household: 'HOUSEHOLD' as TypeEnum
    };
}


