/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Status d\'habitation de l\'emprunteur.
 */
export interface Housing { 
    /**
     * Status d\'habitation.
     */
    housing_status?: Housing.HousingStatusEnum;
    /**
     * Date du dernier changement de status d\'habitation.
     */
    housing_status_since?: string;
}
export namespace Housing {
    export type HousingStatusEnum = 'HOMEOWNER' | 'TENANT' | 'FREE_OF_CHARGE_TENANT' | 'STAFF_HOUSING' | 'OTHER';
    export const HousingStatusEnum = {
        Homeowner: 'HOMEOWNER' as HousingStatusEnum,
        Tenant: 'TENANT' as HousingStatusEnum,
        FreeOfChargeTenant: 'FREE_OF_CHARGE_TENANT' as HousingStatusEnum,
        StaffHousing: 'STAFF_HOUSING' as HousingStatusEnum,
        Other: 'OTHER' as HousingStatusEnum
    };
}


