/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * IBAN structuré
 */
export interface Iban { 
    /**
     * Code pays.
     */
    country_code: string;
    /**
     * Clé de controle.
     */
    control_key: string;
    /**
     * Code banque.
     */
    bank_code: string;
    /**
     * Code guichet.
     */
    agency_code: string;
    /**
     * Numéro de compte.
     */
    account_number: string;
    /**
     * Clé RIB.
     */
    rib_key: string;
}

