/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InsuranceQuestionnaire } from './insuranceQuestionnaire';
import { Address } from './address';
import { Courtesy } from './courtesy';
import { FamilySituation } from './familySituation';
import { ResidencePermit } from './residencePermit';
import { Housing } from './housing';
import { BankInfo } from './bankInfo';


/**
 * Informations relatives à l\'emprunteur personne physique.
 */
export interface Individual { 
    courtesy?: Courtesy;
    /**
     * Prénom.
     */
    first_name?: string;
    /**
     * Nom de famille.
     */
    last_name?: string;
    /**
     * Nom de naissance.
     */
    birth_name?: string;
    /**
     * Date de naissance.
     */
    birth_date?: string;
    /**
     * Pays de naissance.
     */
    birth_place?: string;
    /**
     * Email.
     */
    email?: string;
    /**
     * Numéro de téléphone.
     */
    phone_number?: string;
    residency_address?: Address;
    contact_address?: Address;
    family_situation?: FamilySituation;
    housing?: Housing;
    bank_info?: BankInfo;
    /**
     * Nationalité.
     */
    nationality?: string;
    residence_permit?: ResidencePermit;
    insurance_questionnaire?: InsuranceQuestionnaire;
}

