/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Questions réglementaires permettant d\'effectuer un devis d\'assurance au sein de la simulation.
 */
export interface InsuranceQuestionnaire { 
    /**
     * L\'emprunteur est-il fumeur de cigarettes traditionelles ?
     */
    smoker?: boolean;
    /**
     * L\'emprunteur est-il fumeur de cigarettes électroniques ?
     */
    electronic_smoker?: boolean;
    /**
     * Kilométrage annuel de l\'emprunteur.
     */
    annual_kilometers?: number;
    /**
     * L\'emprunteur pratique t-il des sports risqués ?
     */
    risky_sports_activities?: boolean;
    /**
     * Préciser la hauteur du travail en mètres, en cas de travail en hauteur.
     */
    height_of_work?: number;
    /**
     * L\'emprunteur effectue un travail manuel ?
     */
    manual_labor?: boolean;
    /**
     * L\'emprunteur effectue un travail manuel risqué ?
     */
    risky_manual_labor?: boolean;
    /**
     * L\'emprunteur manipule t-il des produits dangereux ?
     */
    risky_products_handling?: boolean;
    /**
     * Types de métiers considérés comme à risque.
     */
    jobs_at_risk_types?: InsuranceQuestionnaire.JobsAtRiskTypesEnum;
    /**
     * Commentaire.
     */
    comment?: string;
}
export namespace InsuranceQuestionnaire {
    export type JobsAtRiskTypesEnum = 'SECURITY_FIREFIGHTER_POLICE' | 'ARTISTIC_WORK' | 'WORK_WITH_SPIRITUALITY' | 'AVIATION_AND_PLANES' | 'FISHER_MARINE_DOCKWORKER' | 'OIL_GAS_NUCLEAR_SECTOR' | 'PROFESSIONAL_SPORT_PRACTITIONER_TRAINER' | 'ROAD_TRANSPORTER' | 'WORK_WITH_WILD_ANIMALS' | 'WORK_IN_MONTAINS_OR_IN_UNDERGROUND' | 'HUMANITARIAN_WORKER';
    export const JobsAtRiskTypesEnum = {
        SecurityFirefighterPolice: 'SECURITY_FIREFIGHTER_POLICE' as JobsAtRiskTypesEnum,
        ArtisticWork: 'ARTISTIC_WORK' as JobsAtRiskTypesEnum,
        WorkWithSpirituality: 'WORK_WITH_SPIRITUALITY' as JobsAtRiskTypesEnum,
        AviationAndPlanes: 'AVIATION_AND_PLANES' as JobsAtRiskTypesEnum,
        FisherMarineDockworker: 'FISHER_MARINE_DOCKWORKER' as JobsAtRiskTypesEnum,
        OilGasNuclearSector: 'OIL_GAS_NUCLEAR_SECTOR' as JobsAtRiskTypesEnum,
        ProfessionalSportPractitionerTrainer: 'PROFESSIONAL_SPORT_PRACTITIONER_TRAINER' as JobsAtRiskTypesEnum,
        RoadTransporter: 'ROAD_TRANSPORTER' as JobsAtRiskTypesEnum,
        WorkWithWildAnimals: 'WORK_WITH_WILD_ANIMALS' as JobsAtRiskTypesEnum,
        WorkInMontainsOrInUnderground: 'WORK_IN_MONTAINS_OR_IN_UNDERGROUND' as JobsAtRiskTypesEnum,
        HumanitarianWorker: 'HUMANITARIAN_WORKER' as JobsAtRiskTypesEnum
    };
}


