/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Assurance
 */
export interface Insurance { 
    /**
     * Type d\'assurance: sur le capital initial, ou sur le capital restant dû.
     */
    type: Insurance.TypeEnum;
    /**
     * Taux annuel, en %, de l\'assurance, avant multiplication par la quotité. Mettre 0.3 pour 0.3% par exemple.
     */
    rate: number;
    /**
     * Quotité assurée, en %. Mettre 50 pour 50% par exemple.
     */
    quota?: number;
    /**
     * Liste des garanties de l\'assurance emprunteur.
     */
    risks_covered?: Array<Insurance.RisksCoveredEnum>;
    /**
     * Assurance optionnelle ou obligatoire (de cette information dépend son inclusion ou non dans le calcul TAEG).  Mettre à true si l\'assurance est obligatoire.
     */
    mandatory?: boolean;
    /**
     * Assureur.
     */
    company?: string;
    /**
     * Emprunteur lié à cette assurance.
     */
    person?: string;
    /**
     * Commentaire.
     */
    comment?: string;
}
export namespace Insurance {
    export type TypeEnum = 'INITIAL_CAPITAL' | 'REMAINING_CAPITAL';
    export const TypeEnum = {
        InitialCapital: 'INITIAL_CAPITAL' as TypeEnum,
        RemainingCapital: 'REMAINING_CAPITAL' as TypeEnum
    };
    export type RisksCoveredEnum = 'ITT' | 'IPP' | 'IPT' | 'PTIA' | 'DC' | 'PE';
    export const RisksCoveredEnum = {
        Itt: 'ITT' as RisksCoveredEnum,
        Ipp: 'IPP' as RisksCoveredEnum,
        Ipt: 'IPT' as RisksCoveredEnum,
        Ptia: 'PTIA' as RisksCoveredEnum,
        Dc: 'DC' as RisksCoveredEnum,
        Pe: 'PE' as RisksCoveredEnum
    };
}


