/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdministrativeInformation } from './administrativeInformation';
import { ProjectState } from './projectState';
import { LandExpenses } from './landExpenses';
import { Contact } from './contact';


/**
 * Projet d\'achat de terrain.
 */
export interface Land { 
    type?: Land.TypeEnum;
    project_state?: ProjectState;
    administrative_information?: AdministrativeInformation;
    /**
     * Surface du terrain.
     */
    surface?: number;
    seller?: Contact;
    expenses?: LandExpenses;
}
export namespace Land {
    export type TypeEnum = 'LAND';
    export const TypeEnum = {
        Land: 'LAND' as TypeEnum
    };
}


