/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LightFinanceDetails } from './lightFinanceDetails';
import { FinancialResults } from './financialResults';
import { LightPerson } from './lightPerson';


/**
 * Informations relatives à l\'emprunteur personne morale.
 */
export interface LightLegalPerson { 
    type: LightLegalPerson.TypeEnum;
    /**
     * Type de structure.
     */
    structure_type?: LightLegalPerson.StructureTypeEnum;
    /**
     * Associés de la personne morale.
     */
    persons?: Array<LightPerson>;
    financial_results?: FinancialResults;
    finance?: LightFinanceDetails;
}
export namespace LightLegalPerson {
    export type TypeEnum = 'LEGAL_PERSON';
    export const TypeEnum = {
        LegalPerson: 'LEGAL_PERSON' as TypeEnum
    };
    export type StructureTypeEnum = 'SCI' | 'COMPANY' | 'ASSOCIATION' | 'POLITICAL_PARTY' | 'LOCAL_AUTHORITIES';
    export const StructureTypeEnum = {
        Sci: 'SCI' as StructureTypeEnum,
        Company: 'COMPANY' as StructureTypeEnum,
        Association: 'ASSOCIATION' as StructureTypeEnum,
        PoliticalParty: 'POLITICAL_PARTY' as StructureTypeEnum,
        LocalAuthorities: 'LOCAL_AUTHORITIES' as StructureTypeEnum
    };
}


