/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LightOldProperty } from './lightOldProperty';
import { LightBalancingAdjustment } from './lightBalancingAdjustment';
import { LightHouseConstruction } from './lightHouseConstruction';
import { LightHouseholdDetails } from './lightHouseholdDetails';
import { LightWorks } from './lightWorks';
import { LightLand } from './lightLand';
import { LightLegalPerson } from './lightLegalPerson';
import { LightNewProperty } from './lightNewProperty';


/**
 * Dossier emprunteur limité aux informations impactant le plan de financement, pour un financement.
 */
export interface LightCaseFunding { 
    project?: LightHouseConstruction | LightOldProperty | LightNewProperty | LightWorks | LightLand | LightBalancingAdjustment;
    actor?: LightHouseholdDetails | LightLegalPerson;
}

