/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SmoothableCharge } from './smoothableCharge';
import { Insurance } from './insurance';
import { Ira } from './ira';
import { GracePeriod } from './gracePeriod';


/**
 * Prêt à racheter ou à regrouper.
 */
export interface LoanToConsolidate { 
    /**
     * Taux annuel.
     */
    yearly_rate: number;
    /**
     * Durée du prêt en mois.
     */
    duration_months: number;
    /**
     * Capital initial.
     */
    initial_capital: number;
    /**
     * Assurance(s) emprunteur(s).
     */
    insurances?: Array<Insurance>;
    grace_period?: GracePeriod;
    /**
     * Liste du ou des elements sur lesquels lisser le prêt.
     */
    smoothable_elements?: Array<SmoothableCharge>;
    /**
     * Date de la première mensualité.
     */
    first_monthly_payment_date: string;
    ira: Ira;
}

