/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Ira } from './ira';


/**
 * Dépenses résiduelles liées au prêt, dans le cadre d\'un rachat ou d\'un regroupement de crédits.
 */
export interface LoanRemainingCosts { 
    /**
     * Montant du capital restant dû.
     */
    capital: number;
    /**
     * Montant de l\'assurance restant à payer.
     */
    insurance_cost: number;
    /**
     * Montant des intérets restant à payer.
     */
    interest_cost: number;
    ira: Ira;
}

