/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdministrativeInformation } from './administrativeInformation';
import { DpeRate } from './dpeRate';
import { Surfaces } from './surfaces';
import { OldPropertyExpenses } from './oldPropertyExpenses';
import { ProjectState } from './projectState';
import { ConstructionNorms } from './constructionNorms';
import { Contact } from './contact';


/**
 * Projet d\'acquisition d\'un logement ancien.
 */
export interface OldProperty { 
    type: OldProperty.TypeEnum;
    project_state?: ProjectState;
    administrative_information?: AdministrativeInformation;
    surfaces?: Surfaces;
    dpe_rate?: DpeRate;
    /**
     * Date de construction, pour les logements achevés.
     */
    construction_date?: string;
    construction_norm?: ConstructionNorms;
    /**
     * Numéro de lot.
     */
    lot_number?: string;
    /**
     * Nombre de pièces.
     */
    rooms_count?: number;
    seller?: Contact;
    expenses?: OldPropertyExpenses;
}
export namespace OldProperty {
    export type TypeEnum = 'OLD_PROPERTY';
    export const TypeEnum = {
        OldProperty: 'OLD_PROPERTY' as TypeEnum
    };
}


