/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PartnerBillingTier } from './partnerBillingTier';


/**
 * Structure de facturation du partenaire, par type de prêt et par tranches de montants de prêts.   Si aucune structure de facturation n\'existe pour un type de prêt donné, la structure par défaut (définie sans type de prêt) s\'appliquera, si celle-ci existe.  flat_fee et rate s\'appliqueront au niveau du ou des prêts, sous la forme flat_fee + rate * montant_du_prêt, en plus de la facturation par tranches.
 */
export interface PartnerBillingTiersPerLoan { 
    /**
     * Type de prêt.
     */
    type?: PartnerBillingTiersPerLoan.TypeEnum;
    tiers: Array<PartnerBillingTier>;
    /**
     * Part fixe, niveau prêt.
     */
    flat_fee?: number;
    /**
     * Part variable, niveau prêt.
     */
    rate?: number;
    /**
     * Montant maximum du comissionnement de ce partenaire pour ce type de prêt, si un maximum existe.
     */
    limit?: number;
}
export namespace PartnerBillingTiersPerLoan {
    export type TypeEnum = 'FREE_LOAN' | 'BRIDGE_LOAN' | 'PTZ_LOAN' | 'BOSS_LOAN';
    export const TypeEnum = {
        FreeLoan: 'FREE_LOAN' as TypeEnum,
        BridgeLoan: 'BRIDGE_LOAN' as TypeEnum,
        PtzLoan: 'PTZ_LOAN' as TypeEnum,
        BossLoan: 'BOSS_LOAN' as TypeEnum
    };
}


