/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PartnerType } from './partnerType';
import { Address } from './address';
import { BillingRules } from './billingRules';
import { RIB } from './rIB';
import { Contact } from './contact';


/**
 * Partenaire, et sa liste de contacts.
 */
export interface Partner { 
    type: PartnerType;
    /**
     * Nom du partenaire.
     */
    name?: string;
    address?: Address;
    /**
     * Sous-entité: agence, bureau, etc....
     */
    sub_entity?: string;
    /**
     * Agrément ORIAS, ou n\'importe quelle référence légale
     */
    agreement_number?: string;
    main_contact?: Contact;
    /**
     * Liste des contacts au sein du partenaire.
     */
    contacts?: Array<Contact>;
    /**
     * Lien vers le logo du partenaire. Par exemple: https://www.toaztr.com/assets/toaztr_logo.png
     */
    logo_uri?: string;
    /**
     * Addresse du site web du partenaire.
     */
    website?: string;
    partner_billing_rules?: BillingRules;
    customer_billing_rules?: BillingRules;
    rib?: RIB;
    /**
     * Commentaire.
     */
    comment?: string;
}

