/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type de partenaire ou d\'intervenant sur un dossier.
 */
export type PartnerType = 'NOTARY' | 'ESTATE_AGENT' | 'BANK' | 'BROKER' | 'COLLECTOR_ONE_PERCENT_EMPLOYER' | 'HOUSE_BUILDER' | 'DPE_CHECKER' | 'LAND_SURVEYOR' | 'BUSINESS_PROVIDER' | 'ARCHITECT' | 'REAL_ESTATE_DEVELOPER' | 'LAWYER' | 'INSURER' | 'OTHER';

export const PartnerType = {
    Notary: 'NOTARY' as PartnerType,
    EstateAgent: 'ESTATE_AGENT' as PartnerType,
    Bank: 'BANK' as PartnerType,
    Broker: 'BROKER' as PartnerType,
    CollectorOnePercentEmployer: 'COLLECTOR_ONE_PERCENT_EMPLOYER' as PartnerType,
    HouseBuilder: 'HOUSE_BUILDER' as PartnerType,
    DpeChecker: 'DPE_CHECKER' as PartnerType,
    LandSurveyor: 'LAND_SURVEYOR' as PartnerType,
    BusinessProvider: 'BUSINESS_PROVIDER' as PartnerType,
    Architect: 'ARCHITECT' as PartnerType,
    RealEstateDeveloper: 'REAL_ESTATE_DEVELOPER' as PartnerType,
    Lawyer: 'LAWYER' as PartnerType,
    Insurer: 'INSURER' as PartnerType,
    Other: 'OTHER' as PartnerType
};

