/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Address } from './address';
import { Breakup } from './breakup';
import { ForSale } from './forSale';


/**
 * Élément de patrimoine de l\'emprunteur.
 */
export interface PatrimonyItem { 
    /**
     * Type de patrimoine.
     */
    type: PatrimonyItem.TypeEnum;
    breakup?: Breakup;
    /**
     * Valeur: estimée (bien immobilier par exemple) ou de rachat (assurance vie par exemple).
     */
    value: number;
    /**
     * Capital restant dû, si un crédit est toujours en cours.
     */
    remaining_capital?: number;
    /**
     * Date d\'achat (du bien immobilier, des actions...) ou date d\'ouverture (de l\'assurance vie, du PEE...).
     */
    buying_or_opening_date?: string;
    address?: Address;
    /**
     * Présence d\'une hypothèque ?
     */
    is_mortgaged?: boolean;
    /**
     * Mis en vente ?
     */
    is_for_sale?: boolean;
    for_sale?: ForSale;
    /**
     * Commentaire.
     */
    comment?: string;
}
export namespace PatrimonyItem {
    export type TypeEnum = 'LIVRET_A' | 'LDDS' | 'LEP' | 'LIVRET_JEUNE' | 'LIFE_INSURANCE' | 'PEL' | 'CEL' | 'PEE' | 'PEA' | 'PER' | 'CURRENT_ACCOUNT' | 'FAMILY_DONATION' | 'SHARES' | 'SCI_SHARES' | 'SOCIAL_SHARES' | 'JEWELRY' | 'ART_WORK' | 'COLLECTION' | 'REAL_ESTATE_MAIN_PROPERTY' | 'REAL_ESTATE_SECONDARY_PROPERTY' | 'REAL_ESTATE_RENTING_PROPERTY' | 'LAND' | 'PARKING' | 'COMMERCIAL_PREMISES' | 'BUILDING' | 'PROFESSIONAL_REAL_ESTATE' | 'CAPITAL_GOODS' | 'OTHER';
    export const TypeEnum = {
        LivretA: 'LIVRET_A' as TypeEnum,
        Ldds: 'LDDS' as TypeEnum,
        Lep: 'LEP' as TypeEnum,
        LivretJeune: 'LIVRET_JEUNE' as TypeEnum,
        LifeInsurance: 'LIFE_INSURANCE' as TypeEnum,
        Pel: 'PEL' as TypeEnum,
        Cel: 'CEL' as TypeEnum,
        Pee: 'PEE' as TypeEnum,
        Pea: 'PEA' as TypeEnum,
        Per: 'PER' as TypeEnum,
        CurrentAccount: 'CURRENT_ACCOUNT' as TypeEnum,
        FamilyDonation: 'FAMILY_DONATION' as TypeEnum,
        Shares: 'SHARES' as TypeEnum,
        SciShares: 'SCI_SHARES' as TypeEnum,
        SocialShares: 'SOCIAL_SHARES' as TypeEnum,
        Jewelry: 'JEWELRY' as TypeEnum,
        ArtWork: 'ART_WORK' as TypeEnum,
        Collection: 'COLLECTION' as TypeEnum,
        RealEstateMainProperty: 'REAL_ESTATE_MAIN_PROPERTY' as TypeEnum,
        RealEstateSecondaryProperty: 'REAL_ESTATE_SECONDARY_PROPERTY' as TypeEnum,
        RealEstateRentingProperty: 'REAL_ESTATE_RENTING_PROPERTY' as TypeEnum,
        Land: 'LAND' as TypeEnum,
        Parking: 'PARKING' as TypeEnum,
        CommercialPremises: 'COMMERCIAL_PREMISES' as TypeEnum,
        Building: 'BUILDING' as TypeEnum,
        ProfessionalRealEstate: 'PROFESSIONAL_REAL_ESTATE' as TypeEnum,
        CapitalGoods: 'CAPITAL_GOODS' as TypeEnum,
        Other: 'OTHER' as TypeEnum
    };
}


