/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NewProperty } from './newProperty';


/**
 * Projet d\'investissement dans le cadre du dispositif Pinel.
 */
export interface Pinel { 
    type: Pinel.TypeEnum;
    /**
     * Durée du dispositif Pinel: 6, 9 ou 12 ans.
     */
    pinel_duration: Pinel.PinelDurationEnum;
    /**
     * Régime d\'imposition.
     */
    tax_mode?: Pinel.TaxModeEnum;
    /**
     * Loyer mensuel.
     */
    monthly_rent_value: number;
    /**
     * Prévision de l\'évolution annuelle du loyer (en pourcentage: mettre 0.5 pour 0.5%, -10 pour -10%, ...).
     */
    monthly_rent_value_yearly_evolution_rate?: number;
    /**
     * Prévision de l\'évolution annuelle du prix du bien (en pourcentage: mettre 0.5 pour 0.5%, -10 pour -10%, ...).
     */
    price_yearly_evolution_rate?: number;
    /**
     * Charges locatives (en pourcentage du loyer: mettre 13 pour 13% par exemple).
     */
    renting_charges_rate?: number;
    property?: NewProperty;
}
export namespace Pinel {
    export type TypeEnum = 'PINEL';
    export const TypeEnum = {
        Pinel: 'PINEL' as TypeEnum
    };
    export type PinelDurationEnum = 6 | 9 | 12;
    export const PinelDurationEnum = {
        NUMBER_6: 6 as PinelDurationEnum,
        NUMBER_9: 9 as PinelDurationEnum,
        NUMBER_12: 12 as PinelDurationEnum
    };
    export type TaxModeEnum = 'REAL' | 'MICRO_FONCIER';
    export const TaxModeEnum = {
        Real: 'REAL' as TaxModeEnum,
        MicroFoncier: 'MICRO_FONCIER' as TaxModeEnum
    };
}


