/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PinelResultsPinelTable { 
    /**
     * Évolution du prix du logement.
     */
    price_evolution?: Array<number>;
    /**
     * Évolution du loyer.
     */
    renting_evolution?: Array<number>;
    /**
     * Somme des loyers perçus.
     */
    renting_received?: Array<number>;
    /**
     * Somme des intérêts d\'emprunt.
     */
    interests?: Array<number>;
    /**
     * Somme des intérêts d\'emprunt.
     */
    insurances?: Array<number>;
    /**
     * Charges déductibles.
     */
    deductible_charges?: Array<number>;
    /**
     * Résultats locatif: loyer - charges.
     */
    renting_result?: Array<number>;
    /**
     * Impôt sur le résultat locatif.
     */
    tax_on_renting_result?: Array<number>;
    /**
     * Réduction d\'impôt Pinel.
     */
    tax_reduction?: Array<number>;
    /**
     * Impact final sur l\'impôt, incluant loyers et réduction Pinel.
     */
    resulting_tax_impact?: Array<number>;
    /**
     * Besoin de trésorerie.
     */
    treasury?: Array<number>;
}

