/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Insurance } from './insurance';
import { Guaranty } from './guaranty';


/**
 * Prêt à taux zéro du gouvernement, ainsi que sa ou ses assurance(s) et sa garantie.   L\'inclusion de ce prêt dans le plan de financement dépendra au final du résultat de calcul d\'élligibilité et donc des caractéristiques du dossier.
 */
export interface PtzLoan { 
    /**
     * Type de prêt: PTZ.
     */
    type: PtzLoan.TypeEnum;
    /**
     * Assurance(s) emprunteur(s).
     */
    insurances?: Array<Insurance>;
    guaranty?: Guaranty;
}
export namespace PtzLoan {
    export type TypeEnum = 'PTZ_LOAN';
    export const TypeEnum = {
        PtzLoan: 'PTZ_LOAN' as TypeEnum
    };
}


