/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Dans le cadre d\'un prêt à taux variable, période durant la quelle le taux annuel est constant (le taux annuel variant d\'une période à l\'autre).
 */
export interface RatePeriod { 
    /**
     * Taux annuel.
     */
    rate: number;
    /**
     * Indice de départ de la période durant laquelle le taux est appliqué (l\'indice du premier mois est 1).
     */
    period_start: number;
    /**
     * Indice de fin de la période durant laquelle le taux est appliqué.
     */
    period_end: number;
}

