/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Relation avec l\'emprunteur.
 */
export type Relationship = 'SPOUSE' | 'EX-SPOUSE' | 'HUSBAND' | 'EX-HUSBAND' | 'BROTHER' | 'SISTER' | 'MOTHER' | 'FATHER' | 'OTHER';

export const Relationship = {
    Spouse: 'SPOUSE' as Relationship,
    ExSpouse: 'EX-SPOUSE' as Relationship,
    Husband: 'HUSBAND' as Relationship,
    ExHusband: 'EX-HUSBAND' as Relationship,
    Brother: 'BROTHER' as Relationship,
    Sister: 'SISTER' as Relationship,
    Mother: 'MOTHER' as Relationship,
    Father: 'FATHER' as Relationship,
    Other: 'OTHER' as Relationship
};

