/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Meta-données de la ressource
 */
export interface ResourceMeta { 
    /**
     * ETag de la ressource
     */
    etag?: string;
    /**
     * Date de création de la ressource
     */
    created_at?: string;
    /**
     * Utilisateur ayant créé la ressource
     */
    created_by?: string;
    /**
     * Date de dernière modification de la ressource
     */
    last_updated_at?: string;
    /**
     * Utilisateur ayant fait la dernière modification de la ressource
     */
    last_updated_by?: string;
}

