/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Address } from './address';


/**
 * Details professionnels d\'un emprunteur indépendant.
 */
export interface SelfEmployed { 
    /**
     * Type de travailleur.
     */
    type: SelfEmployed.TypeEnum;
    /**
     * Dénomination ou raison sociale.
     */
    name?: string;
    /**
     * Numéro au Registre du Commerce et des Sociétés.
     */
    rcs_number?: string;
    /**
     * Numéro de Siret.
     */
    siret?: string;
    /**
     * Profession.
     */
    profession?: string;
    /**
     * Date de début d\'activité.
     */
    activity_start_date?: string;
    /**
     * Code APE.
     */
    ape_code?: string;
    /**
     * Propriétaire du fond: oui/non.
     */
    business_assets_owner?: boolean;
    /**
     * Valeur du fond.
     */
    business_assets_value?: number;
    /**
     * Existance d\'un nantissement: oui/non.
     */
    collateral?: boolean;
    /**
     * Date de début du bail.
     */
    commercial_lease_start_date?: string;
    /**
     * Date de fin du bail.
     */
    commercial_lease_end_date?: string;
    /**
     * Nom de l\'entreprise.
     */
    company_name?: string;
    /**
     * Nombre d\'employés.
     */
    employees_number?: number;
    /**
     * Forme juridique.
     */
    legal_status?: string;
    /**
     * CRD si le fond est acquis via un crédit.
     */
    remaining_capital?: number;
    /**
     * Loyer annuel.
     */
    rent_amount?: number;
    workplace_address?: Address;
}
export namespace SelfEmployed {
    export type TypeEnum = 'SELFEMPLOYED';
    export const TypeEnum = {
        Selfemployed: 'SELFEMPLOYED' as TypeEnum
    };
}


