/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Objectif de la simulation:  - Minimiser le coût global du plan de financement, et donc saturer la capacitée de remboursement de l\'emprunteur. C\'est à dire que la mensualité maximale donnée en entrée est systématiquement utilisée.  - Maximiser le reste à vivre (et donc minimiser la mensualitée): le plan de financement obtenu est plus long et plus coûteux, mais la mensualité est la plus basse possible, et donc le reste à vivre le meilleur possible. Dans ce cas, la mensualité maximale donnée en entrée n\'est pas utilisée.
 */
export type SimulationObjective = 'MINIMIZE_COST' | 'MINIMIZE_INSTALMENT';

export const SimulationObjective = {
    Cost: 'MINIMIZE_COST' as SimulationObjective,
    Instalment: 'MINIMIZE_INSTALMENT' as SimulationObjective
};

