/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Catégorie socioprofessionnelle des ouvriers.
 */
export interface SocioProfessionalGroupOuvriers { 
    type: SocioProfessionalGroupOuvriers.TypeEnum;
    /**
     * Catégorie socio-profesionnelle.
     */
    category?: SocioProfessionalGroupOuvriers.CategoryEnum;
}
export namespace SocioProfessionalGroupOuvriers {
    export type TypeEnum = 'OUVRIERS';
    export const TypeEnum = {
        Ouvriers: 'OUVRIERS' as TypeEnum
    };
    export type CategoryEnum = 'OUVRIERS_QUALIFIES_DE_TYPE_INDUSTRIEL' | 'OUVRIERS_QUALIFIES_DE_TYPE_ARTISANAL' | 'CHAUFFEURS' | 'OUVRIERS_QUALIFIERS_MANUTENTION_MAGASINAGE_TRANSPORT' | 'OUVRIERS_NON_QUALIFIES_DE_TYPE_INDUSTRIEL' | 'OUVRIERS_NON_QUALIFIES_DE_TYPE_ARTISANAL' | 'OUVRIERS_AGRICOLES';
    export const CategoryEnum = {
        OuvriersQualifiesDeTypeIndustriel: 'OUVRIERS_QUALIFIES_DE_TYPE_INDUSTRIEL' as CategoryEnum,
        OuvriersQualifiesDeTypeArtisanal: 'OUVRIERS_QUALIFIES_DE_TYPE_ARTISANAL' as CategoryEnum,
        Chauffeurs: 'CHAUFFEURS' as CategoryEnum,
        OuvriersQualifiersManutentionMagasinageTransport: 'OUVRIERS_QUALIFIERS_MANUTENTION_MAGASINAGE_TRANSPORT' as CategoryEnum,
        OuvriersNonQualifiesDeTypeIndustriel: 'OUVRIERS_NON_QUALIFIES_DE_TYPE_INDUSTRIEL' as CategoryEnum,
        OuvriersNonQualifiesDeTypeArtisanal: 'OUVRIERS_NON_QUALIFIES_DE_TYPE_ARTISANAL' as CategoryEnum,
        OuvriersAgricoles: 'OUVRIERS_AGRICOLES' as CategoryEnum
    };
}


