/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Catégorie socioprofessionnelle des artisants, commerçants et chefs d\'entreprise.
 */
export interface SocioProfessionalGroupArtisansCommercantsChefsEntreprise { 
    type: SocioProfessionalGroupArtisansCommercantsChefsEntreprise.TypeEnum;
    /**
     * Catégorie socio-profesionnelle.
     */
    category?: SocioProfessionalGroupArtisansCommercantsChefsEntreprise.CategoryEnum;
}
export namespace SocioProfessionalGroupArtisansCommercantsChefsEntreprise {
    export type TypeEnum = 'ARTISANS_COMMERCANTS_CHEFS_DENTREPRISE';
    export const TypeEnum = {
        ArtisansCommercantsChefsDentreprise: 'ARTISANS_COMMERCANTS_CHEFS_DENTREPRISE' as TypeEnum
    };
    export type CategoryEnum = 'ARTISANS' | 'COMMERCANTS_ET_ASSIMILES' | 'CHEFS_ENTREPRISE_10_SALARIES_OU_PLUS';
    export const CategoryEnum = {
        Artisans: 'ARTISANS' as CategoryEnum,
        CommercantsEtAssimiles: 'COMMERCANTS_ET_ASSIMILES' as CategoryEnum,
        ChefsEntreprise10SalariesOuPlus: 'CHEFS_ENTREPRISE_10_SALARIES_OU_PLUS' as CategoryEnum
    };
}


