/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Catégorie socioprofessionnelle des autres personnes sans activité professionnelle.
 */
export interface SocioProfessionalGroupAutresPersonnesSansActiviteProfessionnelle { 
    type: SocioProfessionalGroupAutresPersonnesSansActiviteProfessionnelle.TypeEnum;
    /**
     * Catégorie socio-profesionnelle.
     */
    category?: SocioProfessionalGroupAutresPersonnesSansActiviteProfessionnelle.CategoryEnum;
}
export namespace SocioProfessionalGroupAutresPersonnesSansActiviteProfessionnelle {
    export type TypeEnum = 'AUTRES_PERSONNES_SANS_ACTIVITE_PROFESSIONNELLE';
    export const TypeEnum = {
        AutresPersonnesSansActiviteProfessionnelle: 'AUTRES_PERSONNES_SANS_ACTIVITE_PROFESSIONNELLE' as TypeEnum
    };
    export type CategoryEnum = 'CHOMEURS_AYANT_JAMAIS_TRAVAILLE' | 'MILITAIRES_DU_CONTINGENT' | 'ELEVES_ETUDIANTS' | 'SANS_ACTIVITE_MOINS_60' | 'SANS_ACTIVITE_PLUS_60';
    export const CategoryEnum = {
        ChomeursAyantJamaisTravaille: 'CHOMEURS_AYANT_JAMAIS_TRAVAILLE' as CategoryEnum,
        MilitairesDuContingent: 'MILITAIRES_DU_CONTINGENT' as CategoryEnum,
        ElevesEtudiants: 'ELEVES_ETUDIANTS' as CategoryEnum,
        SansActiviteMoins60: 'SANS_ACTIVITE_MOINS_60' as CategoryEnum,
        SansActivitePlus60: 'SANS_ACTIVITE_PLUS_60' as CategoryEnum
    };
}


