/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Catégorie socioprofessionnelle des professions intermédiaires.
 */
export interface SocioProfessionalGroupProfessionsIntermediaires { 
    type: SocioProfessionalGroupProfessionsIntermediaires.TypeEnum;
    /**
     * Catégorie socio-profesionnelle.
     */
    category?: SocioProfessionalGroupProfessionsIntermediaires.CategoryEnum;
}
export namespace SocioProfessionalGroupProfessionsIntermediaires {
    export type TypeEnum = 'PROFESSIONS_INTERMEDIAIRES';
    export const TypeEnum = {
        ProfessionsIntermediaires: 'PROFESSIONS_INTERMEDIAIRES' as TypeEnum
    };
    export type CategoryEnum = 'PROFESSEURS_DES_ECOLES_INSTITUTEUR_ET_ASSIMILE' | 'PROFESSIONS_INTERMEDIAIRES_DE_LA_SANTE_ET_DU_TRAVAIL_SOCIAL' | 'CLERGE_RELIGIEUX' | 'PROFESSIONS_INTERMEDIAIRES_ADMINISTRATIVES_DE_LA_FONCTION_PUBLIQUE' | 'PROFESSIONS_INTERMEDIAIRES_ADMINISTRATIVES_COMMERCIALES_ENTREPRISES' | 'TECHNICIENS' | 'CONTREMAITRES_AGENTS_DE_MAITRISE';
    export const CategoryEnum = {
        ProfesseursDesEcolesInstituteurEtAssimile: 'PROFESSEURS_DES_ECOLES_INSTITUTEUR_ET_ASSIMILE' as CategoryEnum,
        ProfessionsIntermediairesDeLaSanteEtDuTravailSocial: 'PROFESSIONS_INTERMEDIAIRES_DE_LA_SANTE_ET_DU_TRAVAIL_SOCIAL' as CategoryEnum,
        ClergeReligieux: 'CLERGE_RELIGIEUX' as CategoryEnum,
        ProfessionsIntermediairesAdministrativesDeLaFonctionPublique: 'PROFESSIONS_INTERMEDIAIRES_ADMINISTRATIVES_DE_LA_FONCTION_PUBLIQUE' as CategoryEnum,
        ProfessionsIntermediairesAdministrativesCommercialesEntreprises: 'PROFESSIONS_INTERMEDIAIRES_ADMINISTRATIVES_COMMERCIALES_ENTREPRISES' as CategoryEnum,
        Techniciens: 'TECHNICIENS' as CategoryEnum,
        ContremaitresAgentsDeMaitrise: 'CONTREMAITRES_AGENTS_DE_MAITRISE' as CategoryEnum
    };
}


