/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Catégorie socioprofessionnelle des employés.
 */
export interface SocioProfessionalGroupEmployes { 
    type: SocioProfessionalGroupEmployes.TypeEnum;
    /**
     * Catégorie socio-profesionnelle.
     */
    category?: SocioProfessionalGroupEmployes.CategoryEnum;
}
export namespace SocioProfessionalGroupEmployes {
    export type TypeEnum = 'EMPLOYES';
    export const TypeEnum = {
        Employes: 'EMPLOYES' as TypeEnum
    };
    export type CategoryEnum = 'EMPLOYES_CIVIL_AGENTS_DE_SERVICE_FONCTION_PUBLIQUE' | 'POLICIERS_MILITAIRES' | 'EMPLOYES_ADMINISTRATIFS_ENTREPRISE' | 'EMPLOYES_DE_COMMERCE' | 'PERSONNELS_DES_SERVICES_DIRECTS_AUX_PARTICULIERS';
    export const CategoryEnum = {
        EmployesCivilAgentsDeServiceFonctionPublique: 'EMPLOYES_CIVIL_AGENTS_DE_SERVICE_FONCTION_PUBLIQUE' as CategoryEnum,
        PoliciersMilitaires: 'POLICIERS_MILITAIRES' as CategoryEnum,
        EmployesAdministratifsEntreprise: 'EMPLOYES_ADMINISTRATIFS_ENTREPRISE' as CategoryEnum,
        EmployesDeCommerce: 'EMPLOYES_DE_COMMERCE' as CategoryEnum,
        PersonnelsDesServicesDirectsAuxParticuliers: 'PERSONNELS_DES_SERVICES_DIRECTS_AUX_PARTICULIERS' as CategoryEnum
    };
}


