/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubscriptionType } from './subscriptionType';
import { SubscriptionMeteredItem } from './subscriptionMeteredItem';


/**
 * Souscription Toaztr
 */
export interface Subscription { 
    /**
     * Système qui a créé la souscription.
     */
    source: Subscription.SourceEnum;
    type: SubscriptionType;
    /**
     * Nom de la souscription.
     */
    name?: string;
    /**
     * Status de la souscription.
     */
    status: Subscription.StatusEnum;
    /**
     * Date limite de validité.
     */
    valid_until?: string;
    /**
     * Scopes authorisés pour la souscription.
     */
    scopes: Array<string>;
    /**
     * Nombre d\'items inclus dans la souscription.
     */
    quantity: number;
    /**
     * Nombre d\'items en utilisation.
     */
    used: number;
    metered_items?: Array<SubscriptionMeteredItem>;
}
export namespace Subscription {
    export type SourceEnum = 'STRIPE' | 'MANUAL' | 'MASTER';
    export const SourceEnum = {
        Stripe: 'STRIPE' as SourceEnum,
        Manual: 'MANUAL' as SourceEnum,
        Master: 'MASTER' as SourceEnum
    };
    export type StatusEnum = 'ACTIVE' | 'CLOSED';
    export const StatusEnum = {
        Active: 'ACTIVE' as StatusEnum,
        Closed: 'CLOSED' as StatusEnum
    };
}


