/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdministrativeInformation } from './administrativeInformation';
import { DpeRate } from './dpeRate';
import { Surfaces } from './surfaces';
import { WorksExpenses } from './worksExpenses';
import { ConstructionNorms } from './constructionNorms';


/**
 * Projet de travaux
 */
export interface Works { 
    type: Works.TypeEnum;
    administrative_information?: AdministrativeInformation;
    surfaces?: Surfaces;
    /**
     * Date de construction, pour les logements achevés.
     */
    construction_date?: string;
    construction_norm?: ConstructionNorms;
    /**
     * Date de livraison.
     */
    delivery_date?: string;
    /**
     * Numéro de lot.
     */
    lot_number?: string;
    /**
     * Nombre de pièces.
     */
    rooms_count?: number;
    dpe_rate?: DpeRate;
    expenses?: WorksExpenses;
}
export namespace Works {
    export type TypeEnum = 'WORKS';
    export const TypeEnum = {
        Works: 'WORKS' as TypeEnum
    };
}


