/**
 * Toaztr API
 * # Introduction  Les API **Toaztr** sont documentées au format [OpenAPI](https://www.openapis.org/). Elles sont **accessibles depuis n\'importe quel site ou serveur**, toutes les réponses incluant un header Cross-Origin Resource Sharing adapté, comme spécifié sur la [spécification W3C](https://fetch.spec.whatwg.org/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Zonage.
 */
export type Zone = 'A' | 'A bis' | 'B1' | 'B2' | 'C' | 'DROM';

export const Zone = {
    A: 'A' as Zone,
    ABis: 'A bis' as Zone,
    B1: 'B1' as Zone,
    B2: 'B2' as Zone,
    C: 'C' as Zone,
    Drom: 'DROM' as Zone
};

